[global]
developmentMode = false

[server]
runOnSave = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2563eb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#334155"
